name: Copy to S3

on: [push]
jobs:
  copy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Copy files to S3
        run: |
          rm -rf .github
          rm -f .gitignore
          aws s3 cp . s3://lp-biblia-do-sono-rafael-hoffman/ --recursive --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore"
